name: Docker Build and Push

on:
  release:
    types: [created]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          TAG=${{ github.event.release.tag_name }}
          REPOSITORY_NAME=${{ github.event.repository.name }}
          BUILD_ARG=""
          IMAGE_NAME=$(echo "${{ env.DOCKERHUB_USERNAME }}/${REPOSITORY_NAME}:${TAG}")
          docker build $BUILD_ARG -t $IMAGE_NAME .
          docker push $IMAGE_NAME